server {
    listen 80;
    location / {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
```

**`.env`** (raiz)
```
APP_NAME=FarmaOS
APP_ENV=production
```

**`.gitignore`** (raiz)
```
.env
.idea/
__pycache__/
*.pyc
.DS_Store