name: Deploy FarmaOS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy na DigitalOcean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: root
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/pharmacy-api
            git pull origin main
            k3s kubectl apply -f k8s/nginx-config.yaml
            k3s kubectl apply -f k8s/nginx-deployment.yaml
            k3s kubectl rollout restart deployment/farmaos-nginx
            k3s kubectl rollout status deployment/farmaos-nginx --timeout=90s
            docker compose down
            docker compose up -d --build
            docker save pharmacy-api-api:latest | k3s ctr images import -
            k3s kubectl delete pods -l app=farmaos-api
            k3s kubectl rollout status deployment/farmaos-api --timeout=90s